#...............................................................................
#
#  This file is part of the ECCKey utility.
#
#  ECCKey is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/ecckey/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - source travis/install-$TRAVIS_OS_NAME.sh
    - git clone http://github.com/vovkos/axl

script:
    - THIS_DIR=`pwd`

    - mkdir axl/build
    - cd axl/build
    - cmake ..
    - make

    - cd $THIS_DIR
    - echo "set (AXL_CMAKE_DIR $THIS_DIR/axl/cmake $THIS_DIR/axl/build/cmake)" >> paths.cmake

    - mkdir build
    - cd build
    - cmake ..
    - make
